#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <m64_world_icons.h>

int32_t m64_world_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm m64_world!");

    return 0;
}
